name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  fmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: run fmt
        uses: m3y/rust-just-action@v1
        with:
          command: fmt

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: run lint
        uses: m3y/rust-just-action@v1
        with:
          command: lint

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: run test
        uses: m3y/rust-just-action@v1
        with:
          command: test
